/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./resources/js/components/Album.vue')['default']
    AppFooter: typeof import('./resources/js/components/AppFooter.vue')['default']
    AppHead: typeof import('./resources/js/components/AppHead.vue')['default']
    Bandcamp: typeof import('./resources/js/components/Icons/Bandcamp.vue')['default']
    Facebook: typeof import('./resources/js/components/Icons/Facebook.vue')['default']
    FeaturedItem: typeof import('./resources/js/components/FeaturedItem.vue')['default']
    FormInputField: typeof import('./resources/js/components/Form/InputField.vue')['default']
    FormTextArea: typeof import('./resources/js/components/Form/TextArea.vue')['default']
    FormTextareaField: typeof import('./resources/js/components/Form/TextareaField.vue')['default']
    IconsBandcamp: typeof import('./resources/js/components/Icons/Bandcamp.vue')['default']
    IconsFacebook: typeof import('./resources/js/components/Icons/Facebook.vue')['default']
    IconsSoundcloud: typeof import('./resources/js/components/Icons/Soundcloud.vue')['default']
    IconsSpotify: typeof import('./resources/js/components/Icons/Spotify.vue')['default']
    IconsX: typeof import('./resources/js/components/Icons/X.vue')['default']
    IconsYoutube: typeof import('./resources/js/components/Icons/Youtube.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
    InputField: typeof import('./resources/js/components/Form/InputField.vue')['default']
    InputInput: typeof import('./resources/js/components/Input/Input.vue')['default']
    InputInputField: typeof import('./resources/js/components/Input/InputField.vue')['default']
    NavBar: typeof import('./resources/js/components/NavBar.vue')['default']
    Pagination: typeof import('./resources/js/components/Pagination.vue')['default']
    Project: typeof import('./resources/js/components/Project.vue')['default']
    Soundcloud: typeof import('./resources/js/components/Icons/Soundcloud.vue')['default']
    Spotify: typeof import('./resources/js/components/Icons/Spotify.vue')['default']
    TextareaField: typeof import('./resources/js/components/Form/TextareaField.vue')['default']
    X: typeof import('./resources/js/components/Icons/X.vue')['default']
    Youtube: typeof import('./resources/js/components/Icons/Youtube.vue')['default']
  }
}
